"""Persisted model mappings."""

from game_catalog.persistence.models.facts import (
    AvailabilityOffer,
    FranchiseOwnership,
    GameCompany,
    GameLength,
    GamePlatformLockReason,
    GamePrimaryScore,
    GameScore,
    PlatformLockAssessment,
    PlatformLockReason,
)
from game_catalog.persistence.models.identity import (
    Game,
    GameAlias,
    GameContent,
    GameEdition,
    GameRelation,
    Product,
    Release,
)
from game_catalog.persistence.models.operations import Backup, ExecutionRun, SchemaMetadata
from game_catalog.persistence.models.personal import PersonalCollectionItem
from game_catalog.persistence.models.reference import (
    Company,
    Ecosystem,
    Franchise,
    FranchiseEcosystem,
    Manufacturer,
    Platform,
    Region,
)
from game_catalog.persistence.models.sources import (
    CatalogAssertion,
    CompanyExternalId,
    EditionExternalId,
    FranchiseExternalId,
    GameExternalId,
    PlatformExternalId,
    ProductExternalId,
    RecordSourceLink,
    ReleaseExternalId,
    Source,
    SourceReference,
)

__all__ = [
    "AvailabilityOffer",
    "Backup",
    "CatalogAssertion",
    "Company",
    "CompanyExternalId",
    "Ecosystem",
    "EditionExternalId",
    "ExecutionRun",
    "Franchise",
    "FranchiseEcosystem",
    "FranchiseExternalId",
    "FranchiseOwnership",
    "Game",
    "GameAlias",
    "GameCompany",
    "GameContent",
    "GameEdition",
    "GameExternalId",
    "GameLength",
    "GamePlatformLockReason",
    "GamePrimaryScore",
    "GameRelation",
    "GameScore",
    "Manufacturer",
    "PersonalCollectionItem",
    "Platform",
    "PlatformExternalId",
    "PlatformLockAssessment",
    "PlatformLockReason",
    "Product",
    "ProductExternalId",
    "RecordSourceLink",
    "Region",
    "Release",
    "ReleaseExternalId",
    "SchemaMetadata",
    "Source",
    "SourceReference",
]
